
package teamC;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Teams", targetNamespace = "http://TeamWsServer.ws.training/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Teams {


    /**
     * 
     * @param arg0
     * @return
     *     returns teamC.Team
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "geTeam", targetNamespace = "http://TeamWsServer.ws.training/", className = "teamC.GeTeam")
    @ResponseWrapper(localName = "geTeamResponse", targetNamespace = "http://TeamWsServer.ws.training/", className = "teamC.GeTeamResponse")
    @Action(input = "http://TeamWsServer.ws.training/Teams/geTeamRequest", output = "http://TeamWsServer.ws.training/Teams/geTeamResponse")
    public Team geTeam(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<teamC.Team>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "geTeams", targetNamespace = "http://TeamWsServer.ws.training/", className = "teamC.GeTeams")
    @ResponseWrapper(localName = "geTeamsResponse", targetNamespace = "http://TeamWsServer.ws.training/", className = "teamC.GeTeamsResponse")
    @Action(input = "http://TeamWsServer.ws.training/Teams/geTeamsRequest", output = "http://TeamWsServer.ws.training/Teams/geTeamsResponse")
    public List<Team> geTeams();

}
